### PR TITLE
⬆️ Upgrades ZwaveJS2Mqtt to v6.5.1

### PR DESCRIPTION
**Pull request by geirra**
Update zwavejs2mqtt from 6.5.0 to 6.5.1

# Proposed Changes
Updates zwavejs2mqtt from 6.5.0 to 6.5.1, only minor difference

> (Describe the changes and rationale behind them)
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.5.1

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
@geirra Considering the build doesn't pass, I assume you haven't tested this either?

**Comment by geirra** [comment]
> s, I assume you haven't tested this either?

Yeah sorry about that, jumped the gun on this it seems.  Looking into the build problems.
Will resubmit when i have it fixed

**Comment by frenck** [comment]
Addressed the issue in the current `main` branch.

**Review by frenck — APPROVED** [review]
Thanks, @geirra 👍

**Pull request merged**
