### PR TITLE
Upgrades ZwaveJS2Mqtt to v5.6.0

### PR DESCRIPTION
**Pull request by asucrews**
# Proposed Changes
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.6.0

### CODE REVIEW

**Comment by nemith** [comment]
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.6.0 was just tagged and has zwavejs 8.3.0 which fixes some critical S2 bugs.

**Comment by asucrews** [comment]
looks like 5.6.0 has been removed at this time.

**Comment by MikeAg03** [comment]
5.6.0 looks to be re-released and is likely much more important than 5.5.4 as it fixes S2 bugs.

**Comment by nemith** [comment]
> 5.6.0 looks to be re-released and is likely much more important than 5.5.4 as it fixes S2 bugs.  
Yes S2 bugs is what I am waiting on :)

**Comment by asucrews** [comment]
Add back 5.6.0 @frenck to signoff, and hope this helps is workload

https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v5.6.0

**Review by MikeAg03 — APPROVED** [review]
Simple update to version pulled in.

**Comment by MikeAg03** [comment]
@asucrews it appears you may have to put an appropriate label on the PR.  I believe "dependencies" is the appropriate label for this change.  If you do that, I believe it'll possible go thru the automated workflow to get tested... granted, it appears it'll still need a review with someone with write access and a new release made, but it should move it a few steps forward.

**Comment by asucrews** [comment]
I would to add the label but i cant :( it might be because I am first-time contributor

**Review by Gunsmithy — DISMISSED** [review]

**Comment by mundschenk-at** [comment]
You might want to merge the commits and force-push the branch to get a clean history. Also (extrapolating from previous PRs), it should probably be named "Upgrades ZwaveJS2Mqtt to v5.6.0". 

As for the label to get the workflow to run through, maybe @iantrich, @balloob or @timmo001 would be willing to help out here (since @frenck appears to have been offline for September so far)?

**Comment by frenck** [comment]
> As for the label to get the workflow to run through, maybe @iantrich, @balloob or @timmo001 would be willing to help out here (since @frenck appears to have been offline for September so far)?

I've been on holiday and after that ended up in a hospital for sugergy. Hence I have been offline for a bit. Currently recovering and slowly picking up stuff again.

Will try to pick this one up for tomorrow.

**Comment by mundschenk-at** [comment]
> > As for the label to get the workflow to run through, maybe @iantrich, @balloob or @timmo001 would be willing to help out here (since @frenck appears to have been offline for September so far)?
> 
> I've been on holiday and after that ended up in a hospital for surgery. Hence I have been offline for a bit. Currently recovering and slowly picking up stuff again.

I'm sorry to hear that :( I hope you'll recover quickly!

**Review by frenck — APPROVED** [review]
Thanks, @asucrews 👍

**Pull request merged**
