### PR TITLE
:arrow_up: Upgrades ZwaveJS2Mqtt to v1.4.0

### PR DESCRIPTION
**Pull request by bepsoccer**
# Proposed Changes

Upstream release notes: https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.4.0

### CODE REVIEW

**Comment by bepsoccer** [comment]
Looks like node needs to be bumped to pass the build check, but I didn't want to be presumptive and do that.

**Comment by frenck** [comment]
This bump is most likely incompatible with the current stable Home Assistant release. What have you noticed during testing?

**Comment by bepsoccer** [comment]
I'll withdraw and refrain from trying to contribute.

**Comment by frenck** [comment]
? It was a simple and honest question? 🤷‍♂️

**Pull request closed without merging**
