### PR TITLE
⬆️  Upgrades ZwaveJS2Mqtt to v4.5.0

### PR DESCRIPTION
**Pull request by raman325**
https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v4.5.0

### CODE REVIEW

**Comment by frenck** [comment]
@raman325 Thanks for the PR, however, it isn't upgraded yet because of the build result you see in this PR 😬

**Comment by frenck** [comment]
Rebased

**Review by frenck — APPROVED** [review]
Thanks, @raman325 👍

**Comment by raman325** [comment]
Weird, thought I had already rebased

**Comment by frenck** [comment]
If you did I wouldn't matter, as the main branch was still broken. I rebased after upgrading the base image.

**Comment by raman325** [comment]
Ah 👍

**Pull request merged**
